//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Studio7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Broadcast
    {
        public int Id { get; set; }
        public int Doctor_userId { get; set; }
    
        public virtual Users_Doctor Users_Doctor { get; set; }
    }
}
